//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 10:08:21 ¤U¤È CET 
//


package pubMedCentralJaxbMixing2868029_2584013;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for article-meta element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="article-meta">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}article-id" maxOccurs="unbounded"/>
 *           &lt;element ref="{}article-categories"/>
 *           &lt;element ref="{}title-group"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{}aff"/>
 *             &lt;element ref="{}contrib-group"/>
 *           &lt;/choice>
 *           &lt;element ref="{}author-notes"/>
 *           &lt;element ref="{}pub-date" maxOccurs="unbounded"/>
 *           &lt;element ref="{}volume"/>
 *           &lt;element ref="{}issue"/>
 *           &lt;element ref="{}elocation-id"/>
 *           &lt;element ref="{}history"/>
 *           &lt;element ref="{}permissions"/>
 *           &lt;element ref="{}abstract"/>
 *           &lt;element ref="{}counts"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleId",
    "articleCategories",
    "titleGroup",
    "affOrContribGroup",
    "authorNotes",
    "pubDate",
    "volume",
    "issue",
    "elocationId",
    "history",
    "permissions",
    "_abstract",
    "counts"
})
@XmlRootElement(name = "article-meta")
public class ArticleMeta {

    @XmlElement(name = "article-id", required = true)
    protected List<ArticleId> articleId;
    @XmlElement(name = "article-categories", required = true)
    protected ArticleCategories articleCategories;
    @XmlElement(name = "title-group", required = true)
    protected TitleGroup titleGroup;
    @XmlElements({
        @XmlElement(name = "contrib-group", required = true, type = ContribGroup.class),
        @XmlElement(name = "aff", required = true, type = Aff.class)
    })
    protected List<Object> affOrContribGroup;
    @XmlElement(name = "author-notes", required = true)
    protected AuthorNotes authorNotes;
    @XmlElement(name = "pub-date", required = true)
    protected List<PubDate> pubDate;
    @XmlElement(required = true)
    protected BigInteger volume;
    @XmlElement(required = true)
    protected BigInteger issue;
    @XmlElement(name = "elocation-id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String elocationId;
    @XmlElement(required = true)
    protected History history;
    @XmlElement(required = true)
    protected Permissions permissions;
    @XmlElement(name = "abstract", required = true)
    protected Abstract _abstract;
    @XmlElement(required = true)
    protected Counts counts;

    /**
     * Gets the value of the articleId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleId }
     * 
     * 
     */
    public List<ArticleId> getArticleId() {
        if (articleId == null) {
            articleId = new ArrayList<ArticleId>();
        }
        return this.articleId;
    }

    /**
     * Gets the value of the articleCategories property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleCategories }
     *     
     */
    public ArticleCategories getArticleCategories() {
        return articleCategories;
    }

    /**
     * Sets the value of the articleCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleCategories }
     *     
     */
    public void setArticleCategories(ArticleCategories value) {
        this.articleCategories = value;
    }

    /**
     * Gets the value of the titleGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TitleGroup }
     *     
     */
    public TitleGroup getTitleGroup() {
        return titleGroup;
    }

    /**
     * Sets the value of the titleGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleGroup }
     *     
     */
    public void setTitleGroup(TitleGroup value) {
        this.titleGroup = value;
    }

    /**
     * Gets the value of the affOrContribGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the affOrContribGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAffOrContribGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContribGroup }
     * {@link Aff }
     * 
     * 
     */
    public List<Object> getAffOrContribGroup() {
        if (affOrContribGroup == null) {
            affOrContribGroup = new ArrayList<Object>();
        }
        return this.affOrContribGroup;
    }

    /**
     * Gets the value of the authorNotes property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorNotes }
     *     
     */
    public AuthorNotes getAuthorNotes() {
        return authorNotes;
    }

    /**
     * Sets the value of the authorNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorNotes }
     *     
     */
    public void setAuthorNotes(AuthorNotes value) {
        this.authorNotes = value;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pubDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPubDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PubDate }
     * 
     * 
     */
    public List<PubDate> getPubDate() {
        if (pubDate == null) {
            pubDate = new ArrayList<PubDate>();
        }
        return this.pubDate;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVolume(BigInteger value) {
        this.volume = value;
    }

    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIssue(BigInteger value) {
        this.issue = value;
    }

    /**
     * Gets the value of the elocationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElocationId() {
        return elocationId;
    }

    /**
     * Sets the value of the elocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElocationId(String value) {
        this.elocationId = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
    public History getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
    public void setHistory(History value) {
        this.history = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link Permissions }
     *     
     */
    public Permissions getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Permissions }
     *     
     */
    public void setPermissions(Permissions value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the counts property.
     * 
     * @return
     *     possible object is
     *     {@link Counts }
     *     
     */
    public Counts getCounts() {
        return counts;
    }

    /**
     * Sets the value of the counts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Counts }
     *     
     */
    public void setCounts(Counts value) {
        this.counts = value;
    }

}
