//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 10:08:21 ¤U¤È CET 
//


package pubMedCentralJaxbMixing2868029_2584013;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for author-notes element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="author-notes">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}corresp"/>
 *           &lt;element ref="{}fn"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "corresp",
    "fn"
})
@XmlRootElement(name = "author-notes")
public class AuthorNotes {

    @XmlElement(required = true)
    protected Corresp corresp;
    @XmlElement(required = true)
    protected Fn fn;

    /**
     * Gets the value of the corresp property.
     * 
     * @return
     *     possible object is
     *     {@link Corresp }
     *     
     */
    public Corresp getCorresp() {
        return corresp;
    }

    /**
     * Sets the value of the corresp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Corresp }
     *     
     */
    public void setCorresp(Corresp value) {
        this.corresp = value;
    }

    /**
     * Gets the value of the fn property.
     * 
     * @return
     *     possible object is
     *     {@link Fn }
     *     
     */
    public Fn getFn() {
        return fn;
    }

    /**
     * Sets the value of the fn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fn }
     *     
     */
    public void setFn(Fn value) {
        this.fn = value;
    }

}
