//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 10:08:21 ¤U¤È CET 
//


package pubMedCentralJaxbMixing2868029_2584013;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for back element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="back">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}ack"/>
 *           &lt;element ref="{}fn-group"/>
 *           &lt;element ref="{}ref-list"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ack",
    "fnGroup",
    "refList"
})
@XmlRootElement(name = "back")
public class Back {

    @XmlElement(required = true)
    protected Ack ack;
    @XmlElement(name = "fn-group", required = true)
    protected FnGroup fnGroup;
    @XmlElement(name = "ref-list", required = true)
    protected RefList refList;

    /**
     * Gets the value of the ack property.
     * 
     * @return
     *     possible object is
     *     {@link Ack }
     *     
     */
    public Ack getAck() {
        return ack;
    }

    /**
     * Sets the value of the ack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ack }
     *     
     */
    public void setAck(Ack value) {
        this.ack = value;
    }

    /**
     * Gets the value of the fnGroup property.
     * 
     * @return
     *     possible object is
     *     {@link FnGroup }
     *     
     */
    public FnGroup getFnGroup() {
        return fnGroup;
    }

    /**
     * Sets the value of the fnGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link FnGroup }
     *     
     */
    public void setFnGroup(FnGroup value) {
        this.fnGroup = value;
    }

    /**
     * Gets the value of the refList property.
     * 
     * @return
     *     possible object is
     *     {@link RefList }
     *     
     */
    public RefList getRefList() {
        return refList;
    }

    /**
     * Sets the value of the refList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefList }
     *     
     */
    public void setRefList(RefList value) {
        this.refList = value;
    }

}
