//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 10:08:21 ¤U¤È CET 
//


package pubMedCentralJaxbMixing2868029_2584013;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for front element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="front">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}journal-meta"/>
 *           &lt;element ref="{}article-meta"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journalMeta",
    "articleMeta"
})
@XmlRootElement(name = "front")
public class Front {

    @XmlElement(name = "journal-meta", required = true)
    protected JournalMeta journalMeta;
    @XmlElement(name = "article-meta", required = true)
    protected ArticleMeta articleMeta;

    /**
     * Gets the value of the journalMeta property.
     * 
     * @return
     *     possible object is
     *     {@link JournalMeta }
     *     
     */
    public JournalMeta getJournalMeta() {
        return journalMeta;
    }

    /**
     * Sets the value of the journalMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalMeta }
     *     
     */
    public void setJournalMeta(JournalMeta value) {
        this.journalMeta = value;
    }

    /**
     * Gets the value of the articleMeta property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleMeta }
     *     
     */
    public ArticleMeta getArticleMeta() {
        return articleMeta;
    }

    /**
     * Sets the value of the articleMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleMeta }
     *     
     */
    public void setArticleMeta(ArticleMeta value) {
        this.articleMeta = value;
    }

}
