//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 10:08:21 ¤U¤È CET 
//


package pubMedCentralJaxbMixing2868029_2584013;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for journal-meta element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="journal-meta">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}journal-id" maxOccurs="unbounded"/>
 *           &lt;element ref="{}journal-title-group"/>
 *           &lt;element ref="{}issn"/>
 *           &lt;element ref="{}publisher"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journalId",
    "journalTitleGroup",
    "issn",
    "publisher"
})
@XmlRootElement(name = "journal-meta")
public class JournalMeta {

    @XmlElement(name = "journal-id", required = true)
    protected List<JournalId> journalId;
    @XmlElement(name = "journal-title-group", required = true)
    protected JournalTitleGroup journalTitleGroup;
    @XmlElement(required = true)
    protected Issn issn;
    @XmlElement(required = true)
    protected Publisher publisher;

    /**
     * Gets the value of the journalId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalId }
     * 
     * 
     */
    public List<JournalId> getJournalId() {
        if (journalId == null) {
            journalId = new ArrayList<JournalId>();
        }
        return this.journalId;
    }

    /**
     * Gets the value of the journalTitleGroup property.
     * 
     * @return
     *     possible object is
     *     {@link JournalTitleGroup }
     *     
     */
    public JournalTitleGroup getJournalTitleGroup() {
        return journalTitleGroup;
    }

    /**
     * Sets the value of the journalTitleGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalTitleGroup }
     *     
     */
    public void setJournalTitleGroup(JournalTitleGroup value) {
        this.journalTitleGroup = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * @return
     *     possible object is
     *     {@link Issn }
     *     
     */
    public Issn getIssn() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Issn }
     *     
     */
    public void setIssn(Issn value) {
        this.issn = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link Publisher }
     *     
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publisher }
     *     
     */
    public void setPublisher(Publisher value) {
        this.publisher = value;
    }

}
