//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.22 at 10:08:21 ¤U¤È CET 
//


package pubMedCentralJaxbMixing2868029_2584013;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pubMedCentralJaxbMixing2868029_2584013 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ElocationId_QNAME = new QName("", "elocation-id");
    private final static QName _JournalTitle_QNAME = new QName("", "journal-title");
    private final static QName _Subject_QNAME = new QName("", "subject");
    private final static QName _Issue_QNAME = new QName("", "issue");
    private final static QName _PublisherName_QNAME = new QName("", "publisher-name");
    private final static QName _Surname_QNAME = new QName("", "surname");
    private final static QName _Label_QNAME = new QName("", "label");
    private final static QName _GivenNames_QNAME = new QName("", "given-names");
    private final static QName _Italic_QNAME = new QName("", "italic");
    private final static QName _Sup_QNAME = new QName("", "sup");
    private final static QName _Lpage_QNAME = new QName("", "lpage");
    private final static QName _AddrLine_QNAME = new QName("", "addr-line");
    private final static QName _Source_QNAME = new QName("", "source");
    private final static QName _Email_QNAME = new QName("", "email");
    private final static QName _Underline_QNAME = new QName("", "underline");
    private final static QName _Volume_QNAME = new QName("", "volume");
    private final static QName _CopyrightStatement_QNAME = new QName("", "copyright-statement");
    private final static QName _Month_QNAME = new QName("", "month");
    private final static QName _Role_QNAME = new QName("", "role");
    private final static QName _Year_QNAME = new QName("", "year");
    private final static QName _Day_QNAME = new QName("", "day");
    private final static QName _PublisherLoc_QNAME = new QName("", "publisher-loc");
    private final static QName _Fpage_QNAME = new QName("", "fpage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pubMedCentralJaxbMixing2868029_2584013
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Contrib }
     * 
     */
    public Contrib createContrib() {
        return new Contrib();
    }

    /**
     * Create an instance of {@link Aff }
     * 
     */
    public Aff createAff() {
        return new Aff();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link JournalMeta }
     * 
     */
    public JournalMeta createJournalMeta() {
        return new JournalMeta();
    }

    /**
     * Create an instance of {@link Front }
     * 
     */
    public Front createFront() {
        return new Front();
    }

    /**
     * Create an instance of {@link Ack }
     * 
     */
    public Ack createAck() {
        return new Ack();
    }

    /**
     * Create an instance of {@link PubId }
     * 
     */
    public PubId createPubId() {
        return new PubId();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link Tbody }
     * 
     */
    public Tbody createTbody() {
        return new Tbody();
    }

    /**
     * Create an instance of {@link AuthorNotes }
     * 
     */
    public AuthorNotes createAuthorNotes() {
        return new AuthorNotes();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Corresp }
     * 
     */
    public Corresp createCorresp() {
        return new Corresp();
    }

    /**
     * Create an instance of {@link Alternatives }
     * 
     */
    public Alternatives createAlternatives() {
        return new Alternatives();
    }

    /**
     * Create an instance of {@link JournalId }
     * 
     */
    public JournalId createJournalId() {
        return new JournalId();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Col }
     * 
     */
    public Col createCol() {
        return new Col();
    }

    /**
     * Create an instance of {@link Thead }
     * 
     */
    public Thead createThead() {
        return new Thead();
    }

    /**
     * Create an instance of {@link ContribGroup }
     * 
     */
    public ContribGroup createContribGroup() {
        return new ContribGroup();
    }

    /**
     * Create an instance of {@link ObjectId }
     * 
     */
    public ObjectId createObjectId() {
        return new ObjectId();
    }

    /**
     * Create an instance of {@link TitleGroup }
     * 
     */
    public TitleGroup createTitleGroup() {
        return new TitleGroup();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link RefList }
     * 
     */
    public RefList createRefList() {
        return new RefList();
    }

    /**
     * Create an instance of {@link Etal }
     * 
     */
    public Etal createEtal() {
        return new Etal();
    }

    /**
     * Create an instance of {@link ExtLink }
     * 
     */
    public ExtLink createExtLink() {
        return new ExtLink();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link Media }
     * 
     */
    public Media createMedia() {
        return new Media();
    }

    /**
     * Create an instance of {@link Bold }
     * 
     */
    public Bold createBold() {
        return new Bold();
    }

    /**
     * Create an instance of {@link TableWrap }
     * 
     */
    public TableWrap createTableWrap() {
        return new TableWrap();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link PageCount }
     * 
     */
    public PageCount createPageCount() {
        return new PageCount();
    }

    /**
     * Create an instance of {@link PmcArticleset }
     * 
     */
    public PmcArticleset createPmcArticleset() {
        return new PmcArticleset();
    }

    /**
     * Create an instance of {@link AltTitle }
     * 
     */
    public AltTitle createAltTitle() {
        return new AltTitle();
    }

    /**
     * Create an instance of {@link TableWrapFoot }
     * 
     */
    public TableWrapFoot createTableWrapFoot() {
        return new TableWrapFoot();
    }

    /**
     * Create an instance of {@link ArticleMeta }
     * 
     */
    public ArticleMeta createArticleMeta() {
        return new ArticleMeta();
    }

    /**
     * Create an instance of {@link ArticleId }
     * 
     */
    public ArticleId createArticleId() {
        return new ArticleId();
    }

    /**
     * Create an instance of {@link ArticleTitle }
     * 
     */
    public ArticleTitle createArticleTitle() {
        return new ArticleTitle();
    }

    /**
     * Create an instance of {@link Fn }
     * 
     */
    public Fn createFn() {
        return new Fn();
    }

    /**
     * Create an instance of {@link Fig }
     * 
     */
    public Fig createFig() {
        return new Fig();
    }

    /**
     * Create an instance of {@link PersonGroup }
     * 
     */
    public PersonGroup createPersonGroup() {
        return new PersonGroup();
    }

    /**
     * Create an instance of {@link Colgroup }
     * 
     */
    public Colgroup createColgroup() {
        return new Colgroup();
    }

    /**
     * Create an instance of {@link SubjGroup }
     * 
     */
    public SubjGroup createSubjGroup() {
        return new SubjGroup();
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link Counts }
     * 
     */
    public Counts createCounts() {
        return new Counts();
    }

    /**
     * Create an instance of {@link Xref }
     * 
     */
    public Xref createXref() {
        return new Xref();
    }

    /**
     * Create an instance of {@link SupplementaryMaterial }
     * 
     */
    public SupplementaryMaterial createSupplementaryMaterial() {
        return new SupplementaryMaterial();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link PubDate }
     * 
     */
    public PubDate createPubDate() {
        return new PubDate();
    }

    /**
     * Create an instance of {@link Sec }
     * 
     */
    public Sec createSec() {
        return new Sec();
    }

    /**
     * Create an instance of {@link ArticleCategories }
     * 
     */
    public ArticleCategories createArticleCategories() {
        return new ArticleCategories();
    }

    /**
     * Create an instance of {@link MixedCitation }
     * 
     */
    public MixedCitation createMixedCitation() {
        return new MixedCitation();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link NamedContent }
     * 
     */
    public NamedContent createNamedContent() {
        return new NamedContent();
    }

    /**
     * Create an instance of {@link Graphic }
     * 
     */
    public Graphic createGraphic() {
        return new Graphic();
    }

    /**
     * Create an instance of {@link JournalTitleGroup }
     * 
     */
    public JournalTitleGroup createJournalTitleGroup() {
        return new JournalTitleGroup();
    }

    /**
     * Create an instance of {@link FnGroup }
     * 
     */
    public FnGroup createFnGroup() {
        return new FnGroup();
    }

    /**
     * Create an instance of {@link Back }
     * 
     */
    public Back createBack() {
        return new Back();
    }

    /**
     * Create an instance of {@link Issn }
     * 
     */
    public Issn createIssn() {
        return new Issn();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elocation-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createElocationId(String value) {
        return new JAXBElement<String>(_ElocationId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "journal-title")
    public JAXBElement<String> createJournalTitle(String value) {
        return new JAXBElement<String>(_JournalTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subject")
    public JAXBElement<String> createSubject(String value) {
        return new JAXBElement<String>(_Subject_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "issue")
    public JAXBElement<BigInteger> createIssue(BigInteger value) {
        return new JAXBElement<BigInteger>(_Issue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publisher-name")
    public JAXBElement<String> createPublisherName(String value) {
        return new JAXBElement<String>(_PublisherName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "surname")
    public JAXBElement<String> createSurname(String value) {
        return new JAXBElement<String>(_Surname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "given-names")
    public JAXBElement<String> createGivenNames(String value) {
        return new JAXBElement<String>(_GivenNames_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "italic")
    public JAXBElement<String> createItalic(String value) {
        return new JAXBElement<String>(_Italic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sup")
    public JAXBElement<String> createSup(String value) {
        return new JAXBElement<String>(_Sup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lpage")
    public JAXBElement<BigInteger> createLpage(BigInteger value) {
        return new JAXBElement<BigInteger>(_Lpage_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addr-line")
    public JAXBElement<String> createAddrLine(String value) {
        return new JAXBElement<String>(_AddrLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "underline")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUnderline(String value) {
        return new JAXBElement<String>(_Underline_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "volume")
    public JAXBElement<BigInteger> createVolume(BigInteger value) {
        return new JAXBElement<BigInteger>(_Volume_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "copyright-statement")
    public JAXBElement<String> createCopyrightStatement(String value) {
        return new JAXBElement<String>(_CopyrightStatement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "month")
    public JAXBElement<BigInteger> createMonth(BigInteger value) {
        return new JAXBElement<BigInteger>(_Month_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "role")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRole(String value) {
        return new JAXBElement<String>(_Role_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "year")
    public JAXBElement<BigInteger> createYear(BigInteger value) {
        return new JAXBElement<BigInteger>(_Year_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "day")
    public JAXBElement<BigInteger> createDay(BigInteger value) {
        return new JAXBElement<BigInteger>(_Day_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publisher-loc")
    public JAXBElement<String> createPublisherLoc(String value) {
        return new JAXBElement<String>(_PublisherLoc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fpage")
    public JAXBElement<String> createFpage(String value) {
        return new JAXBElement<String>(_Fpage_QNAME, String.class, null, value);
    }

}
