// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.26 at 06:35:42 PM CET 
//
package eSearchResultJaxb;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}Count"/>
 *             &lt;sequence minOccurs="0">
 *               &lt;element ref="{}RetMax"/>
 *               &lt;element ref="{}RetStart"/>
 *               &lt;element ref="{}QueryKey" minOccurs="0"/>
 *               &lt;element ref="{}WebEnv" minOccurs="0"/>
 *               &lt;element ref="{}IdList"/>
 *               &lt;element ref="{}TranslationSet"/>
 *               &lt;element ref="{}TranslationStack" minOccurs="0"/>
 *               &lt;element ref="{}QueryTranslation"/>
 *             &lt;/sequence>
 *           &lt;/sequence>
 *           &lt;element ref="{}ERROR"/>
 *         &lt;/choice>
 *         &lt;element ref="{}ErrorList" minOccurs="0"/>
 *         &lt;element ref="{}WarningList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "count",
    "retMax",
    "retStart",
    "queryKey",
    "webEnv",
    "idList",
    "translationSet",
    "translationStack",
    "queryTranslation",
    "error",
    "errorList",
    "warningList"
})
@XmlRootElement(name = "eSearchResult")
public class ESearchResult {

    @XmlElement(name = "Count")
    protected String count;
    @XmlElement(name = "RetMax")
    protected String retMax;
    @XmlElement(name = "RetStart")
    protected String retStart;
    @XmlElement(name = "QueryKey")
    protected String queryKey;
    @XmlElement(name = "WebEnv")
    protected String webEnv;
    @XmlElement(name = "IdList")
    protected IdList idList;
    @XmlElement(name = "TranslationSet")
    protected TranslationSet translationSet;
    @XmlElement(name = "TranslationStack")
    protected TranslationStack translationStack;
    @XmlElement(name = "QueryTranslation")
    protected String queryTranslation;
    @XmlElement(name = "ERROR")
    protected String error;
    @XmlElement(name = "ErrorList")
    protected ErrorList errorList;
    @XmlElement(name = "WarningList")
    protected WarningList warningList;

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the retMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetMax() {
        return retMax;
    }

    /**
     * Sets the value of the retMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetMax(String value) {
        this.retMax = value;
    }

    /**
     * Gets the value of the retStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetStart() {
        return retStart;
    }

    /**
     * Sets the value of the retStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetStart(String value) {
        this.retStart = value;
    }

    /**
     * Gets the value of the queryKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryKey() {
        return queryKey;
    }

    /**
     * Sets the value of the queryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryKey(String value) {
        this.queryKey = value;
    }

    /**
     * Gets the value of the webEnv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebEnv() {
        return webEnv;
    }

    /**
     * Sets the value of the webEnv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebEnv(String value) {
        this.webEnv = value;
    }

    /**
     * Gets the value of the idList property.
     * 
     * @return
     *     possible object is
     *     {@link IdList }
     *     
     */
    public IdList getIdList() {
        return idList;
    }

    /**
     * Sets the value of the idList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdList }
     *     
     */
    public void setIdList(IdList value) {
        this.idList = value;
    }

    /**
     * Gets the value of the translationSet property.
     * 
     * @return
     *     possible object is
     *     {@link TranslationSet }
     *     
     */
    public TranslationSet getTranslationSet() {
        return translationSet;
    }

    /**
     * Sets the value of the translationSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslationSet }
     *     
     */
    public void setTranslationSet(TranslationSet value) {
        this.translationSet = value;
    }

    /**
     * Gets the value of the translationStack property.
     * 
     * @return
     *     possible object is
     *     {@link TranslationStack }
     *     
     */
    public TranslationStack getTranslationStack() {
        return translationStack;
    }

    /**
     * Sets the value of the translationStack property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslationStack }
     *     
     */
    public void setTranslationStack(TranslationStack value) {
        this.translationStack = value;
    }

    /**
     * Gets the value of the queryTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryTranslation() {
        return queryTranslation;
    }

    /**
     * Sets the value of the queryTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryTranslation(String value) {
        this.queryTranslation = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERROR() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERROR(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the errorList property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorList }
     *     
     */
    public ErrorList getErrorList() {
        return errorList;
    }

    /**
     * Sets the value of the errorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorList }
     *     
     */
    public void setErrorList(ErrorList value) {
        this.errorList = value;
    }

    /**
     * Gets the value of the warningList property.
     * 
     * @return
     *     possible object is
     *     {@link WarningList }
     *     
     */
    public WarningList getWarningList() {
        return warningList;
    }

    /**
     * Sets the value of the warningList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningList }
     *     
     */
    public void setWarningList(WarningList value) {
        this.warningList = value;
    }

}
